sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

install: true

stages:
  - build
  - integration tests
  - name: docs
    if: fork = false AND branch = master
  - name: deploy
    if: fork = false AND tag =~ ^hoopoe-profiler-

# template for caching the gradle
_cache_gradle: &_cache_gradle
  before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  cache:
    directories:
      - $HOME/.gradle/caches/
      - $HOME/.gradle/wrapper/

# template for integration tests for sql plugin
_sql_integration_tests: &_sql_integration_tests
  script:
    - ./gradlew hoopoe-sql-queries-plugin:clean hoopoe-sql-queries-plugin:integration-tests
  <<: *_cache_gradle

jobs:
  include:
    - stage: build
      before_install:
        # codacy coverage
        - sudo apt-get install jq
        - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
      script:
        - ./gradlew clean build
      <<: *_cache_gradle
      after_success:
        # codecov coverage
        - bash <(curl -s https://codecov.io/bash)
        # codacy coverage
        - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r hoopoe-core-tests/build/reports/jacoco/test/jacocoTestReport.xml
        - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r hoopoe-sql-queries-plugin/build/reports/jacoco/test/jacocoTestReport.xml
        - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r hoopoe-classloader/build/reports/jacoco/test/jacocoTestReport.xml

    - stage: integration tests
      script:
        - ./gradlew clean integration-tests
      <<: *_cache_gradle

    - <<: *_sql_integration_tests
      env: ITEST_DB=postgres

    - <<: *_sql_integration_tests
      env: ITEST_DB=mysql

    - stage: docs
      language: ruby
      rvm: 2.4.1
      jdk:
      cache: bundler
      before_install:
        # deploy keys for github pages
        - openssl aes-256-cbc -K $encrypted_5a0f048e2914_key -iv $encrypted_5a0f048e2914_iv
          -in .deploy_key.enc -out .deploy_key -d
        - chmod 600 .deploy_key
        # rvm for jekyll
        - gem install jekyll bundler
      script:
        - cd ./docs/ && bundle && bundle exec rake deploy

    - stage: deploy
      script:
        - ./gradlew bintrayUpload
      <<: *_cache_gradle