language: java

jdk:
  - oraclejdk8

script:
- ./gradlew clean
- ./gradlew assemble
- ./gradlew check

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  # codecov coverage
  - bash <(curl -s https://codecov.io/bash)
  # codacy coverage
  - curl -sL https://github.com/jpm4j/jpm4j.installers/raw/master/dist/biz.aQute.jpm.run.jar >jpm4j.jar
  - java -jar jpm4j.jar -u init
  - rm jpm4j.jar
  - ~/bin/jpm install com.codacy:codacy-coverage-reporter:assembly
  - ~/bin/codacy-coverage-reporter -l Java -r hoopoe-core-tests/build/reports/jacoco/test/jacocoTestReport.xml