language: java

jdk:
  - oraclejdk8

before_install:
  # deploy keys for github pages
  - openssl aes-256-cbc -K $encrypted_5a0f048e2914_key -iv $encrypted_5a0f048e2914_iv
    -in .deploy_key.enc -out .deploy_key -d
  - chmod 600 .deploy_key
  # codacy coverage
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
  # rvm for jekyll
  - gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
  - \curl -sSL https://get.rvm.io | sed -E s/_rvm_print_headline/_rvm_version/ | bash -s stable --ruby=2.4.1
  - gem install jekyll bundler

script:
  # let's check gradle version
  - ./gradlew --version
  # build the project
  - ./gradlew clean
  - ./gradlew assemble
  - ./gradlew check
  # build the gh-pages
  - cd ./docs/ && bundle

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.rvm/

after_success:
  # codecov coverage
  - bash <(curl -s https://codecov.io/bash)
  # codacy coverage
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r hoopoe-core-tests/build/reports/jacoco/test/jacocoTestReport.xml
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r hoopoe-sql-queries-plugin/build/reports/jacoco/test/jacocoTestReport.xml
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r hoopoe-classloader/build/reports/jacoco/test/jacocoTestReport.xml