sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

install: true

jobs:
  include:
    - stage: build
      before_install:
        # codacy coverage
        - sudo apt-get install jq
        - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
      script:
        - ./gradlew --build-scan clean build
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
      after_success:
        # codecov coverage
        - bash <(curl -s https://codecov.io/bash)
        # codacy coverage
        - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r hoopoe-core-tests/build/reports/jacoco/test/jacocoTestReport.xml
        - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r hoopoe-sql-queries-plugin/build/reports/jacoco/test/jacocoTestReport.xml
        - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r hoopoe-classloader/build/reports/jacoco/test/jacocoTestReport.xml

    - stage: integration tests
      script:
        - ./gradlew --build-scan clean integration-tests
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/

    - env: ITEST_DB=postgres
      script:
        - ./gradlew --build-scan hoopoe-sql-queries-plugin:clean hoopoe-sql-queries-plugin:integration-tests
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/

    - env: ITEST_DB=mysql
      script:
        - ./gradlew --build-scan hoopoe-sql-queries-plugin:clean hoopoe-sql-queries-plugin:integration-tests
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/

    - stage: docs
      language: ruby
      rvm: 2.4.1
      cache: bundler
      before_install:
        # deploy keys for github pages
        - openssl aes-256-cbc -K $encrypted_5a0f048e2914_key -iv $encrypted_5a0f048e2914_iv
          -in .deploy_key.enc -out .deploy_key -d
        - chmod 600 .deploy_key
        # rvm for jekyll
        - gem install jekyll bundler
      script:
        - cd ./docs/ && bundle && bundle exec rake deploy