require 'rake-jekyll'

# This task builds the Jekyll site and deploys it to a remote Git repository.
# It's preconfigured to be used with GitHub and Travis CI.
# See http://github.com/jirutka/rake-jekyll for more options.
Rake::Jekyll::GitDeployTask.new(:deploy) do |t|
  t.ssh_key_file = '../.deploy_key'
  t.committer = 'orange-buffalo <orange-buffalo@users.noreply.github.com>'
end